In [13]:
import math

def r(x):
    t = 1.0
    while abs(x) > 1:
        x /= 10
        t *= 10
    while abs(x) < 0.1:
        x *= 10
        t /= 10
    return round(x, 11)*t

def f(x):
    t = r(math.tan(x**2))
    return r(r(r(x) + 1) - t)
    
def fp(x):
    c0 = r((math.cos(r(x**2))**2))
    print(c0)
    c = r(2*x*r((1/c0)))
    print(c)
    return r(1 - c)

In [14]:
a = 1
b = 1.1
xs = [a, a + (b-a)/4, a + 3*(b-a)/4, b]
ys = [f(x) for x in xs]
ys

[0.4425922753, 0.2791574684, -0.193636909, -0.550324595]

In [29]:
def calc_nevil(Q, xs, i,j, x):
    print(i, j)
    print(f"(x-x_{i-j})Q_"+"{"+f"{i},{j-1}" + "}" + f" - (x- x_{i})Q_"+"{"+f"{i-1},{j-1}" + "}", f"x_{i}-x_{i-j}")
    if j == 1:
        print(f"(x-{xs[i-j]}){Q[j-1][i]} - (x-{xs[i]}){Q[j-1][i-1]}", f"{xs[i]}-{xs[i-j]}")
    else:
        print(f"(x-{xs[i-j]})Q_"+"{"+f"{i},{j-1}" + "}" + f"- (x-{xs[i]})Q_"+"{"+f"{i-1},{j-1}" + "}", f"{xs[i]}-{xs[i-j]}")
#     print(f"({x}-{xs[i-j]}){Q[j-1][i]} - ({x}-{xs[i]}){Q[j-1][i-1]}", f"({xs[i]}-{xs[i-j]})")
#     return round((((x-xs[i-j])*Q[j-1][i]) - ((x-xs[i])*Q[j-1][i-1]))/(xs[i]-xs[i-j]), 10)

def partial_nevil(Q, xs, i, j, x):
    return r((r(r(x-xs[i])*Q[i+1][j]) - r(r(x-xs[j])*Q[i][j-1]))/r(xs[j] - xs[i]))

def nevil(ys, xs, x):
    Q = [[0]*len(xs) for _ in xs]
    for i in range(len(xs)):
        Q[i][i] = ys[i]
    for i in range(1, len(xs)):
        for j in range(len(xs) - i):
            Q[j][j+i] = partial_nevil(Q, xs, j, j+i, x)
    return Q

Q = [ys]
Q11 = calc_nevil(Q, xs, 1, 1, 0)
Q21 = calc_nevil(Q, xs, 2, 1, 0)
Q31 = calc_nevil(Q, xs, 3, 1, 0)
Q.append([Q11, Q21, Q31])
Q22 = calc_nevil(Q, xs, 2, 2, 0)
Q32 = calc_nevil(Q, xs, 3, 2, 0)
Q.append([Q22, Q32])
Q33 = calc_nevil(Q, xs, 3, 3, 0)

1 1
(x-x_0)Q_{1,0} - (x- x_1)Q_{0,0} x_1-x_0
(x-1)0.2791574684 - (x-1.025)0.4425922753 1.025-1
2 1
(x-x_1)Q_{2,0} - (x- x_2)Q_{1,0} x_2-x_1
(x-1.025)-0.193636909 - (x-1.0750000000000002)0.2791574684 1.0750000000000002-1.025
3 1
(x-x_2)Q_{3,0} - (x- x_3)Q_{2,0} x_3-x_2
(x-1.0750000000000002)-0.550324595 - (x-1.1)-0.193636909 1.1-1.0750000000000002
2 2
(x-x_0)Q_{2,1} - (x- x_2)Q_{1,1} x_2-x_0
(x-1)Q_{2,1}- (x-1.0750000000000002)Q_{1,1} 1.0750000000000002-1
3 2
(x-x_1)Q_{3,1} - (x- x_3)Q_{2,1} x_3-x_1
(x-1.025)Q_{3,1}- (x-1.1)Q_{2,1} 1.1-1.025
3 3
(x-x_0)Q_{3,2} - (x- x_3)Q_{2,2} x_3-x_0
(x-1)Q_{3,2}- (x-1.1)Q_{2,2} 1.1-1


In [22]:
xs[0] * ys[1] - xs[1] * ys[0]

-0.17449961378249995

In [30]:
def divideddiff(xs, ys):
    F = [ys]
#     print(f"{ys}")
    for i in range(1, len(xs)):
        fp = []
        for j in range(len(xs) - i):
            a = (F[i-1][j+1] - F[i-1][j])
            b = (xs[i+j] - xs[j])
            ans = round(a/b, 10)
            fp.append(ans)
#             print("$F_{" + f"{i}, {j}" + "} =" + "\dfrac{ F_{" + f"{i-1},{j+1}" + "} - " + "F_{" + f"{i-1}, {j}" + "}}{" + f"x_{i+j} - x_{j}" + "} = " + "\dfrac{" + f"{F[i-1][j+1]} - {F[i-1][j]}" + "}{" + f"{xs[i+j]} - {xs[j]}"+ "} = " + f"{ans}$\\\\")
        F.append(fp)
#     print("P(x) = ", end="")
#     for i in range(len(xs)):
#         print(f"{F[i][0]} \\times ", end="")
#         for j in range(i+1):
#             print(f"(x-{xs[j]})", end="")
#         print(" + ", end="")
    return F

for x in divideddiff(xs, ys):
    print(x)

[0.4425922753, 0.2791574684, -0.193636909, -0.550324595]
[-6.537392276, -9.455887548, -14.26750744]
[-38.9132702933, -64.1549318933]
[-252.416616]


0.4425922753
0.2791574684
0.0730296383
-0.193636909
-0.550324595


0.002617100946250001

In [50]:
import numpy as np
import scipy as sp
import math

fours = [1]
for i in range(10):
    fours.append(fours[-1]*4)

def richardson_step(Y0, Y1, i):
    a = (fours[i])*Y1 - Y0
    b = fours[i]-1
    return a/b

def richardson(ys):
    n = len(ys)
    Y = []
    for i in range(n):
        ans = []
        for j in range(n-i):
            if i == 0:
                ans.append(ys[j])
            else:
                ans.append(richardson_step(Y[i-1][j], Y[i-1][j+1], i))
        Y.append(ans)
    return Y


def trapezoidal(h, ys):
    return h*(2*sum(ys) - ys[0] - ys[-1])/2


def ramburg(f, h, a, n):
    sums = 0
    for i in range(n + 1):
#         print(f(a+i*h))
        if i == 0 or i == n:
            sums += f(a + i*h)
        else:
            sums += 2*f(a+i*h)
    return h*sums/2
h = 0.1
h*(f(a) + f(b))/2
Y0 = ramburg(f, h, a, 1)
Y1 = ramburg(f, h/2, a, 2)
Y2 = ramburg(f, h/4, a, 4)
ys = [Y0, Y1, Y2]
richardson(ys)

[[-0.005386615984999999, 0.0009581739224999997, 0.002617100946250001],
 [0.003073103891666666, 0.003170076620833335],
 [0.003176541469444446]]

In [51]:
import numpy as np
import scipy as sp
import math

m = np.array([
    [2, 0, -1, 6],
    [4, -7, 2, -23],
    [-2, -1, 7, -11],
],dtype=np.float)

def make_uptri(m, mode="normal"):
    # normal, partial, scaledpartial
    coeffs = []
    for i in range(m.shape[0]):
        coeff = [0] * i + [1]
        if mode == "normal":
            j = i
            while m[i][i] == 0 and j < m.shape[0]:
                if m[j][i] != 0:
                    a = m[i, :].copy()
                    m[i, :] = m[j, :]
                    m[j, :] = a
                j += 1
        elif mode == "partial":
            max_ind = i
            j = i
            while j < m.shape[0]:
                if m[j][i] > m[max_ind][i]:
                    max_ind = j
                j += 1
            a = m[max_ind, :].copy()
            m[max_ind, :] = m[i, :]
            m[i, :] = a
        elif mode == "scaledpartial":
            max_ind = i
            j = i
            while j < m.shape[0]:
                if m[j][i]/max(m[j, :]) > m[max_ind][i]/max(m[max_ind, :]):
                    max_ind = j
                j += 1
            a = m[max_ind, :].copy()
            m[max_ind, :] = m[i, :]
            m[i, :] = a
            
        for j in range(i+1, m.shape[0]):
            coeff.append(m[j][i]/m[i][i])
            m[j, :] = m[j, :] - (m[j][i]/m[i][i])*m[i, :]
        coeffs.append(coeff.copy())
    return m, coeffs

def gauss_elim(m, mode="normal"):
    m, coeffs = make_uptri(m, mode)
    x = [0] * m.shape[0]
    x[-1] = m[-1, -1]/m[-1,-2]
    for i in range(m.shape[0] - 2, -1, -1):
        x[i] = (m[i, m.shape[1]-1] - sum(m[i, i+1:-1] * x[i+1:]))/m[i][i]
    return m, x, coeffs

gauss_elim(m.copy(), "normal")

(array([[  2.        ,   0.        ,  -1.        ,   6.        ],
        [  0.        ,  -7.        ,   4.        , -35.        ],
        [  0.        ,   0.        ,   5.42857143,   0.        ]]),
 [3.0, 5.0, 0.0],
 [[1, 2.0, -1.0], [0, 1, 0.14285714285714285], [0, 0, 1]])

In [55]:
def jacobi(m, b, x0, n):
    for i in range(m.shape[0]):
        b[i] = b[i]/m[i, i]
        m[i] = np.divide(m[i, :], m[i, i])
        m[i, i] = 0
    x = b - np.matmul(m, x0)
    for i in range(n):
        x = b - np.matmul(m, x)
    return x


def gausssidel(m, b, x0, n):
    for i in range(m.shape[0]):
        b[i] = b[i]/m[i, i]
        m[i, :] = np.divide(m[i, :], m[i, i])
        m[i, i] = 0
    x = x0
    for i in range(n):
        for j in range(m.shape[0]):
            x[j] = b[j] - np.matmul(m[j, :], x)
        print(x)
    return x

m = np.array([
    [2, 0, -1, 6],
    [4, -7, 2, -23],
    [-2, -1, 7, -11],
],dtype=np.float)

# print(jacobi(m[:,:-1].copy(), m[:,-1].copy(), np.array([0]*m.shape[0], dtype=np.float), 10))
print(gausssidel(m[:,:-1].copy(), m[:,-1].copy(), np.array([0]*m.shape[0], dtype=np.float), 2))

[ 3.00000000e+00  5.00000000e+00 -2.22044605e-16]
[ 3.00000000e+00  5.00000000e+00 -2.22044605e-16]
[ 3.00000000e+00  5.00000000e+00 -2.22044605e-16]
